# Generated by Django 4.1.5 on 2023-02-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_message_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
